### ISSUE TITLE
Results are not comparable

### ISSUE THREAD

**Issue by mkouba** [mbosecke/template-benchmark#2]
The output is not the same for all templating engines.

stocks.mustache.html:

1. `${["odd", "even"][item_index%2]}` is ignored so don't get the correct class for odd/even rows
2. `${item_index + 1}` is ignored so don't get the index
3. negative values are not wrapped with `<td class="minus">`

You should either remove these parts from all templates or implement this with mustache.java (I think you would have to implement some `TemplateFunction` to get the same functionality).

Also I would add a test to compare the output of all benchmarks.

**Comment by mbosecke** [comment]
Fixed by #3
