### ISSUE TITLE
Mustache doing too much pre-processing

### ISSUE THREAD

**Issue by mbosecke** [mbosecke/template-benchmark#4]
As brought up by @mkouba in pull request #3, my recent modifications might have given mustache an unfair advantage. Before the benchmark begins it does some [pre-processing](https://github.com/mbosecke/template-benchmark/blob/master/src/main/java/com/mitchellbosecke/benchmark/Mustache.java#L119) on the data; processing that other templates don't have a chance to do until the are being timed.

**Comment by mbosecke** [comment]
The solution could be as simple as moving line [42](https://github.com/mbosecke/template-benchmark/blob/master/src/main/java/com/mitchellbosecke/benchmark/Mustache.java#L42) to be within the actual benchmarked method.

**Comment by mkouba** [comment]
Well, I don't think this will have a big impact. I just wanted to point out that one can get better performance but the code is more difficult to write and maintain, i.e. the usability should be comparable as well. That's all :wink:
